language: scala

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

scala:
- 2.11.12
- 2.12.8
- 2.13.0

jdk:
  - oraclejdk8

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "++ ${TRAVIS_SCALA_VERSION}!" testSequential
