language: scala

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.cache/coursier

scala:
- 2.11.12
- 2.12.10
- 2.13.1

jdk:
  - openjdk8

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "++ ${TRAVIS_SCALA_VERSION}!" testSequential
