name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 3 * * 4'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: 11
        distribution: temurin
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - run: sbt -v
           scalafmtSbtCheck
           "+ scalafmtCheckAll"
           "+ msgpack4zPlayJVM/test"
           "+ msgpack4zPlayJS/test"
           "+ msgpack4zPlayNative/test"
